app:
  name: mas-system
  environment: production

llm:
  provider: lmstudio
  base_url: http://localhost:1234/v1
  model: gpt-4-turbo-preview
  temperature: 0.7
  max_tokens: 4000

database:
  url: postgresql://user:pass@host:5432/db

redis:
  url: redis://host:6379